-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.polls (
  id text primary key,
  title text not null check (char_length(title) between 1 and 60),
  option_a_name text not null default 'A'
    check (char_length(option_a_name) between 1 and 30),
  option_b_name text not null default 'B'
    check (char_length(option_b_name) between 1 and 30),
  option_a_label text not null default 'A',
  option_b_label text not null default 'B',
  image_a text not null,
  image_b text not null,
  votes_a bigint not null default 0 check (votes_a >= 0),
  votes_b bigint not null default 0 check (votes_b >= 0),
  created_at timestamptz not null default now()
);

-- These ALTER statements make the file safe to run over the earlier MVP schema.
alter table public.polls
  add column if not exists option_a_name text not null default 'A',
  add column if not exists option_b_name text not null default 'B',
  add column if not exists option_a_label text not null default 'A',
  add column if not exists option_b_label text not null default 'B',
  add column if not exists votes_a bigint not null default 0,
  add column if not exists votes_b bigint not null default 0;

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  poll_id text not null references public.polls(id) on delete cascade,
  voter_id text not null check (char_length(voter_id) between 1 and 100),
  choice text not null check (choice in ('A', 'B')),
  created_at timestamptz not null default now(),
  unique (poll_id, voter_id)
);

create index if not exists votes_poll_choice_idx
  on public.votes (poll_id, choice);

-- Backfill counters if this project previously used the MVP votes table.
update public.polls p
set
  votes_a = (
    select count(*) from public.votes v
    where v.poll_id = p.id and v.choice = 'A'
  ),
  votes_b = (
    select count(*) from public.votes v
    where v.poll_id = p.id and v.choice = 'B'
  );

-- One transaction handles duplicate protection and counter increments.
drop function if exists public.cast_poll_vote(text, text, text);

create function public.cast_poll_vote(
  p_poll_id text,
  p_voter_id text,
  p_choice text
)
returns table (
  duplicate boolean,
  saved_choice text,
  votes_a bigint,
  votes_b bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  if p_choice not in ('A', 'B') then
    raise exception 'Invalid vote choice' using errcode = '22023';
  end if;

  if not exists (select 1 from public.polls where id = p_poll_id) then
    raise exception 'Poll not found' using errcode = 'P0002';
  end if;

  insert into public.votes (poll_id, voter_id, choice)
  values (p_poll_id, p_voter_id, p_choice)
  on conflict (poll_id, voter_id) do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count = 1 then
    update public.polls as target
    set
      votes_a = target.votes_a + case when p_choice = 'A' then 1 else 0 end,
      votes_b = target.votes_b + case when p_choice = 'B' then 1 else 0 end
    where target.id = p_poll_id;

    return query
      select false, p_choice, p.votes_a, p.votes_b
      from public.polls p
      where p.id = p_poll_id;
  else
    return query
      select true, v.choice, p.votes_a, p.votes_b
      from public.votes v
      join public.polls p on p.id = v.poll_id
      where v.poll_id = p_poll_id and v.voter_id = p_voter_id;
  end if;
end;
$$;

alter table public.polls enable row level security;
alter table public.votes enable row level security;

revoke all on table public.polls from anon, authenticated;
revoke all on table public.votes from anon, authenticated;
revoke all on function public.cast_poll_vote(text, text, text)
  from public, anon, authenticated;
grant execute on function public.cast_poll_vote(text, text, text)
  to service_role;

-- Public image reads are required because shared poll pages display these URLs.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'poll-images',
  'poll-images',
  true,
  6291456,
  array['image/jpeg']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
