-- Run once in Supabase SQL Editor.
-- Adds minimal page-view tracking without changing existing poll tables.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  pathname text not null check (
    pathname = '/' or pathname ~ '^/p/[a-f0-9]{8}$'
  ),
  poll_id text references public.polls(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

create index if not exists page_views_poll_id_idx
  on public.page_views (poll_id);

alter table public.page_views enable row level security;
revoke all on table public.page_views from anon, authenticated;
